apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game
spec:
  selector:
    matchLabels:
      app: 2048-game
  replicas: 1 
  template: 
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - name: 2048-game
        image: sreedhar8897/2048-game:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: 2048-game
spec:
  type: LoadBalancer
  selector:
    app: 2048-game
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
